__version__: 1.1.0
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  # resize and crop by https://pytorch.org/blog/how-to-train-state-of-the-art-models-using-torchvision-latest-primitives/
  - __class_fullname__: albumentations.augmentations.geometric.resize.Resize
    always_apply: false
    height: 232
    width: 232
    p: 1.0
  - __class_fullname__: albumentations.augmentations.crops.transforms.CenterCrop
    height: 224
    width: 224
    p: 1.0
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    max_pixel_value: 255
    always_apply: true
    p: 1
  - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
    always_apply: true
    p: 1